name: ting_maker
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  change_app_package_name: ^1.1.0
  logger: ^2.2.0
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  geolocator: ^11.0.0
  connectivity_plus: ^6.0.2
  toggle_switch: ^2.3.0
  firebase_messaging: ^14.8.1
  animated_text_kit: ^4.2.2
  infinite_scroll_pagination: ^4.0.0
  firebase_core: ^2.29.0
  shared_preferences: ^2.2.2
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.8
  roundcheckbox: ^2.0.5
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  package_info_plus: ^7.0.0
  flutter_naver_map: ^1.2.2
  intl: ^0.18.1
  crop_your_image: ^1.0.2
  geocoding: ^3.0.0
  sqflite: ^2.3.3
  path: ^1.9.0
  socket_io_client: ^2.0.3+1
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/image/
# fonts:
#   - family: Pretendard
#     fonts:
#       - asset: assets/font/Pretendard-Light.otf
#         weight: 300
#       - asset: assets/font/Pretendard-Regular.otf
#         weight: 400
#       - asset: assets/font/Pretendard-SemiBold.otf
#         weight: 600
#       - asset: assets/font/Pretendard-Bold.otf
#         weight: 700
