name: ting_maker
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get: ^4.6.6

  logger: ^2.2.0
  intl: ^0.19.0
  path: ^1.9.0

  dio: ^5.4.3+1
  socket_io_client: ^2.0.3+1

  geolocator: ^11.0.0
  geojson: ^1.0.0
  flutter_naver_map: ^1.2.2

  firebase_core: ^2.29.0
  firebase_messaging: ^14.8.1

  permission_handler: ^11.3.1

  image_picker: ^1.0.8
  crop_your_image: ^1.0.2
  flutter_svg: ^2.0.10+1
  extended_image: ^8.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.3

  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

  change_app_package_name: ^1.1.0
  connectivity_plus: ^6.0.2
  device_info_plus: ^10.1.0
  package_info_plus: ^7.0.0

  smooth_page_indicator: ^1.1.0
  roundcheckbox: ^2.0.5
  animated_text_kit: ^4.2.2
  infinite_scroll_pagination: ^4.0.0
  auto_size_text: ^3.0.0
  animated_toggle_switch: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter_launcher_icons:
  image_path_android: 'assets/splash/app_icon.png'
  image_path_ios: 'assets/splash/app_icon.png'
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#00BFFE'
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#FFFFFF'
  image: assets/splash/splash3.png
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/splash/splash3.png
    color: '#FFFFFF'
    fullscreen: true
    android_gravity: center
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/image/
  fonts:
    - family: HomeNavi
      fonts:
        - asset: assets/fonts/HomeNavi.ttf
