/// Flutter icons HomeNavi
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeNavi
///      fonts:
///       - asset: fonts/HomeNavi.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class HomeNavi {
  HomeNavi._();

  static const _kFontFam = 'HomeNavi';
  static const String? _kFontPkg = null;

  static const IconData doc_text = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_outline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
