// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZx0jDBWZAm7pEbPJXmc952k956NbHOVw',
    appId: '1:311743264528:web:274d39b846a8f94d2a1795',
    messagingSenderId: '311743264528',
    projectId: 'tingproject11',
    authDomain: 'tingproject11.firebaseapp.com',
    storageBucket: 'tingproject11.appspot.com',
    measurementId: 'G-4FD3R23WM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApczTPVUBo13LaAdbEPCXocvTST0dMQgA',
    appId: '1:311743264528:android:b89c29f44be4eada2a1795',
    messagingSenderId: '311743264528',
    projectId: 'tingproject11',
    storageBucket: 'tingproject11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcH1Lwzn0ww8JkoizOrmz9M0tRju781ng',
    appId: '1:311743264528:ios:737dfb16ffec10eb2a1795',
    messagingSenderId: '311743264528',
    projectId: 'tingproject11',
    storageBucket: 'tingproject11.appspot.com',
    iosBundleId: 'com.modyland.ting',
  );
}
